---
# Samba configuration variables
samba_group: sambajako
samba_share_path: /srv/samba/shared
samba_share_name: shared

samba_users: "{{ vault_samba_users | default([]) }}"

backup_destination: /backup/samba
backup_script_path: /home/vagrant/scripts
backup_time_hour: 2
backup_time_minute: 0



