---
# Nginx configuration variables
nginx_user_group: developers
nginx_user: webmaster
nginx_user_password: "{{ vault_nginx_user_password }}"

web_root: /srv/www
web_html: /srv/www/html/
web_logs: /srv/www/logs/

ssl_cert_dir: /etc/ssl/rainomalabra/certs
ssl_key_dir: /etc/ssl/rainomalabra/private
ssl_cert_file: "{{ ssl_cert_dir }}/rainomalabra.crt"
ssl_key_file: "{{ ssl_key_dir }}/rainomalabra.key"

server_name: rainomalabra.local
server_ip: 192.168.56.10

# SSL certificate details
ssl_country: FI
ssl_state: Uusimaa
ssl_locality: Helsinki
ssl_organization: Rainomalabra
ssl_organizational_unit: IT
ssl_common_name: rainomalabra.local
ssl_validity_days: 365
