---
vault_user_passwords:
  sambauser1: "SambaPass123!"
  sambauser2: "SambaPass456!"
  webmaster: "WebMaster2026!"
  developer1: "DevPass2026!"

vault_samba_passwords:
  sambauser1: "SambaPass123!"
  sambauser2: "SambaPass456!"

vault_backup_ssh_private_key: ""
vault_backup_ssh_public_key: ""
vault_ssl_key_password: ""
vault_root_password: "RootPass2026!"

 


