$ANSIBLE_VAULT;1.1;AES256
33343837666564653732633037373231383136626165393962326538653439663439323862373962
6637356562366462313637353831396635373063323734330a626664303639613136393736343137
64323964306565303966373631316662373031303361326138636364623837663136353265646339
3464303565393661340a343363396639323364663234636464396363336635373762373134323162
63353330333265623633653730343337656132313363646166306565333966363936663139633564
65346338363632323436383464363966346637313535663330313939386335346530373330333464
38656361623231653263333063383631376137646238356333333031636337306464343130643432
33396366653763303539336331356330636461623966303462316362383939306635643031393736
32396435373364366337646230333135643365366136376339353933616665363037666539633932
61626662303030376462623863656163386137326631633265643539306363316265323834653234
33623236366365663235323135316563343634343036633334343030396366393466646262353237
39343534376139346435313935653732343364343862346337393865623232343563386338313866
31343736376337356239663464383530643433333361316430313235633364393838
