---
# K3s configuration
k3s_version: v1.28.5+k3s1
k3s_server_ip: 192.168.56.10
k3s_token_file: /var/lib/rancher/k3s/server/node-token

# Nginx deployment
k3s_namespace: web
nginx_replicas: 2
nginx_image: nginx:alpine


