---
- name: Include master setup
  include_tasks: master.yml
  when: "'managers' in group_names"

- name: Include worker setup
  include_tasks: worker.yml
  when: "'workers' in group_names"

- name: Include deployment 
  include_tasks: deploy.yml 
  when: "'managers' in group_names"
  run_once: true
