---
- name: Firewall Setup
  hosts: all 
  become: yes 
  vars_files: 
    - ./group_vars/all.yml

  pre_tasks: 
    - name: Update apt cache
      apt: 
        update_cache: yes 
        cache_valid_time: 3600 

  roles:
    - ./roles/firewall
